
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/trendsinsight-76709/rag-bot:latest', 
    '-f', 'app/Dockerfile', 
    '.'                      
  ]

images:
- 'gcr.io/trendsinsight-76709/rag-bot:latest'
