version: '3.8'

services:

  db:
    image: postgres:13-alpine 
    container_name: rag_postgres_db
    restart: always
    environment:

      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:

      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: ./app 
    container_name: rag_telegram_bot
    restart: always
    env_file:
      - .env 
    volumes:
    
      - ./data:/data
    depends_on:
      - db 


volumes:
  db_data:
